/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package especialidades;

import clinica.daos.EspecialidadeDao;
import entidades.Especialidade;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ehf_v
 */
public class ListagemEspecialidade extends javax.swing.JFrame {

    private List<Especialidade> itemsEspecialidades;
    private EspecialidadeDao especialidadeDao;
    private DefaultTableModel modelo;

    /**
     * Creates new form ListagemEspecialidade
     */
public ListagemEspecialidade() {
    initComponents();
    inicializarTabela();
    inicializarespecialidadeDao();
    carregarListaEspecialidades();
    carregarDadosNaTabela();

    // Adiciona o ActionListener para o botão Salvar
    salvarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salvarButtonActionPerformed(evt);
        }
    });
}
    private void inicializarespecialidadeDao() {
        // O construtor de EspecialidadeDao não lança mais SQLException diretamente.
        // A exceção é lançada pelos métodos que interagem com o banco de dados.
        this.especialidadeDao = new EspecialidadeDao();
    }

    private void inicializarTabela() {
        String[] colunas = {"ID", "Nome"};
        this.modelo = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1; // Permite edição apenas da coluna 'Nome'
            }
        };
        especialidadesTable.setModel(modelo);
    }

public void carregarListaEspecialidades() {
    try {
        itemsEspecialidades = especialidadeDao.listarTodas();
    } catch (SQLException exception) { 
        JOptionPane.showMessageDialog(null, "Erro ao carregar os dados: " + exception.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        exception.printStackTrace();
    }
}

public void carregarDadosNaTabela() {
    modelo.setRowCount(0); // Limpa as linhas existentes
    for (Especialidade e : itemsEspecialidades) {
        Object[] linha = {e.getId(), e.getNome()};
        modelo.addRow(linha);
    }
}

public void atualizarTabela() {
    carregarListaEspecialidades();
    carregarDadosNaTabela();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        especialidadesTable = new javax.swing.JTable();
        editarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        especialidadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ));
        especialidadesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        especialidadesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(especialidadesTable);

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirButton)
                        .addGap(18, 18, 18)
                        .addComponent(salvarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        int linhaSelecionada = especialidadesTable.getSelectedRow();
        if (linhaSelecionada != -1) {
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja excluir esta especialidade?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                excluirEspecialidade(linhaSelecionada);
                itemsEspecialidades.remove(linhaSelecionada);
                modelo.removeRow(linhaSelecionada); // Correção aqui
                // this.carregarDadosNaTabela(); // Não é mais necessário, pois removemos a linha diretamente do modelo
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
        }

    }//GEN-LAST:event_excluirButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        int selectedRow = especialidadesTable.getSelectedRow();
        if (selectedRow >= 0) {
            JOptionPane.showMessageDialog(this, "Agora você pode editar os dados diretamente na tabela.", "Editar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    private void excluirEspecialidade(int linhaSelecionada) {
        try {
            this.especialidadeDao.deletar(itemsEspecialidades.get(linhaSelecionada).getId());
        } catch (SQLException exception) { 
            JOptionPane.showMessageDialog(null, "Erro ao excluir especialidade!" + exception.getMessage());
            // dispose(); // Não é ideal fechar a janela em caso de erro de exclusão
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemEspecialidade().setVisible(true);
            }
        });
    }
    
        private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = especialidadesTable.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                // Força a finalização da edição na tabela
                if (especialidadesTable.isEditing()) {
                    especialidadesTable.getCellEditor().stopCellEditing();
                }
                
                // Obtém os dados da linha selecionada
                int id = (int) modelo.getValueAt(selectedRow, 0);
                String nome = (String) modelo.getValueAt(selectedRow, 1);

                // Valida o campo nome
                if (nome == null || nome.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "O nome da especialidade não pode estar vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Log para depuração
                System.out.println("ID da especialidade a ser atualizada: " + id);
                System.out.println("Novo nome da especialidade: " + nome);

                // Atualiza o objeto Especialidade
                Especialidade especialidade = itemsEspecialidades.get(selectedRow);
                especialidade.setNome(nome.trim());

                // Tenta atualizar no banco de dados
                especialidadeDao.atualizar(especialidade);

                // Atualiza a tabela localmente
                modelo.setValueAt(nome.trim(), selectedRow, 1);
                JOptionPane.showMessageDialog(this, "Especialidade atualizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar alterações: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para salvar as alterações.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarButton;
    private javax.swing.JTable especialidadesTable;
    private javax.swing.JButton excluirButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
